version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: Install Dependency
          command: npm install
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
            - ~/workspace/dist
          force: yes
